apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-service-bus-orders-wid
spec:
  podIdentity:
    provider: azure-workload
    identityId: 9c4f3781-ed9f-41a2-b8f1-c3fb193c5152
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: order-scaler-wid
spec:
  scaleTargetRef:
    name: order-processor
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: azure-servicebus
    metadata:
      namespace: fabmedical-aiw
      queueName: orders
      messageCount: '50'
    authenticationRef:
      name: trigger-auth-service-bus-orders-wid
